---
title: "Gaston Sanchez's instructional materials for STAT 20"
---

A friendly reminder to myself when teaching [STAT 20](https://stat20.berkeley.edu/), and the reason why I use my own set of custom slides:

>
| The world provides a million ways, for a human heart to grow.
| There is no single compass, no mandatory flow.
|
<!-- | So find your own bright river, and just keep swimming on,
| and let your spirit guide you, into the light of dawn.
|-->
| Follow your own drumbeat, until the day is gone,
| whatever makes you happy, whatever turns you on.
|
| _Gas & Gem_



### Understanding the World with Data

- [Understanding the world](1-questions-and-data/01-understanding-the-world/slides.html){target="_blank"}

- [Taxonomy of Data](1-questions-and-data/02-taxonomy-of-data/slides.html){target="_blank"}


### Summarizing Data

- [Summarizing Categorical Data](2-summarizing-data/01-summarizing-categorical-data/slides.html){target="_blank"}

- [Summarizing Numerical Data](2-summarizing-data/02-summarizing-numerical-data/slides.html){target="_blank"}

- [A Grammar of Graphics](2-summarizing-data/03-a-grammar-of-graphics/slides.html){target="_blank"}

- [Data Manipulation](2-summarizing-data/04-data-manipulation/slides.html){target="_blank"}

- [Data Pipelines](2-summarizing-data/05-data-pipelines/slides.html){target="_blank"}

- [Summarizing Associations](2-summarizing-data/06-summarizing-associations/slides.html){target="_blank"}

- [Multiple Linear Regression](2-summarizing-data/07-multiple-linear-regression/slides.html){target="_blank"}


### Probability

- [Intro to Probability](3-probability/01-chance-intro/slides.html){target="_blank"}

- [Computing Probabilities](3-probability/02-cond-prob-indep/slides.html){target="_blank"}

- [Probability Distributions](3-probability/03-probability-dsns/slides.html){target="_blank"}

- [Random Variables](3-probability/04-random-variables/slides.html){target="_blank"}

- [Expected Value and Variance](3-probability/05-ev-sd/slides.html){target="_blank"}


### Generalization

- Coming soon

- Coming soon


### Causation

- Coming soon

- Coming soon


### Prediction

- Coming soon

- Coming soon


### Quiz Slides

- [Quiz](quiz-slides/quiz-slides.html)

